site_name: The XeroLinux Wiki
site_description: XeroLinux Project Documentation.
site_url: https://wiki.xerolinux.xyz

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette:
    scheme: slate
    primary: indigo
  features:
   - navigation.top
   - navigation.footer
   - navigation.indexes
   - navigation.sections
   - content.code.copy
   - content.code.annotate
   - content.tabs.link
   - glightbox
   - search.suggest
   - search.highlight
   - search.share

plugins:
  - search
  - macros
  - autorefs
  - social
  - glightbox
  - mkdocs-video:
      is_video: false
      video_muted: false
      video_controls: True
      css_style:
        width: "100%"
        height: 22.172vw;
  - literate-nav:
      nav_file: SUMMARY.md

markdown_extensions:

  # Python Markdown
   - abbr
   - admonition
   - attr_list
   - def_list
   - footnotes
   - md_in_html
   - toc:
      permalink: true

  # Python Markdown Extensions
   - pymdownx.arithmatex:
       generic: true
   - pymdownx.betterem:
       smart_enable: all
   - pymdownx.caret
   - pymdownx.details
   - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
   - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
   - pymdownx.inlinehilite
   - pymdownx.keys
   - pymdownx.mark
   - pymdownx.smartsymbols
   - pymdownx.superfences
   - pymdownx.tabbed:
       alternate_style: true
   - pymdownx.tasklist:
       custom_checkbox: true
   - pymdownx.tilde

extra_javascript:
    - js/github-commit-info.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/xerolinux
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/XeroLinuxOfficial
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/xerolinuxop
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@xerolinux

# Copyright
copyright: Copyright &copy; <a href="https://xerolinux.xyz" target="_blank"><strong>XeroLinux Group</strong></a>.
